# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 13:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, default=0.0, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DecimalField(decimal_places=2, default=0.0, max_digits=99)),
                ('provisional', models.DecimalField(decimal_places=2, default=0.0, max_digits=99)),
                ('banked', models.DecimalField(decimal_places=2, default=0.0, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name='BetContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BetPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')], default='H', max_length=1)),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Accumulator')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=255)),
                ('awayteam', models.CharField(max_length=255)),
                ('homenumerator', models.IntegerField(default=0)),
                ('homedenominator', models.IntegerField(default=1)),
                ('drawnumerator', models.IntegerField(default=0)),
                ('drawdenominator', models.IntegerField(default=1)),
                ('awaynumerator', models.IntegerField(default=0)),
                ('awaydenominator', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('deadline_date', models.DateField(default=datetime.date(2018, 8, 5))),
                ('deadline_time', models.TimeField(default=datetime.time(12, 0))),
                ('spiel', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('numerator', models.IntegerField(default=0)),
                ('denominator', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.BetContainer')),
                ('long_special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.LongSpecial')),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('allowance', models.DecimalField(decimal_places=2, default=100.0, max_digits=99)),
                ('created_gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek')),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('completed_gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek')),
                ('long_special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')], default='H', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weekly_allowance', models.DecimalField(decimal_places=2, default=100.0, max_digits=99)),
                ('public', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='season_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='longspecial',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.LongSpecialContainer'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Season'),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
        migrations.AddField(
            model_name='betpart',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game'),
        ),
        migrations.AddField(
            model_name='betcontainer',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
        migrations.AddField(
            model_name='betcontainer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='gameweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accumulator',
            name='bet_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.BetContainer'),
        ),
    ]
