# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='player',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='season',
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
