# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('bets', '0002_auto_20180805_1413'),
    ]

    database_operations = [
        migrations.AlterModelTable('accumulator', 'gambling_accumulator'),
        migrations.AlterModelTable('betcontainer', 'gambling_betcontainer'),
        migrations.AlterModelTable('betpart', 'gambling_betpart'),
        migrations.AlterModelTable('longspecial', 'gambling_longspecial'),
        migrations.AlterModelTable('longspecialbet', 'gambling_longspecialbet'),
        migrations.AlterModelTable('longspecialcontainer', 'gambling_longspecialcontainer'),
        migrations.AlterModelTable('longspecialresult', 'gambling_longspecialresult'),
    ]

    state_operations = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
