# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 08:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_rename_tables'),
        ('gambling', '0001_initial'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='accumulator',
            name='bet_container',
        ),
        migrations.RemoveField(
            model_name='betcontainer',
            name='gameweek',
        ),
        migrations.RemoveField(
            model_name='betcontainer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='betpart',
            name='accumulator',
        ),
        migrations.RemoveField(
            model_name='betpart',
            name='game',
        ),
        migrations.RemoveField(
            model_name='longspecial',
            name='container',
        ),
        migrations.RemoveField(
            model_name='longspecialbet',
            name='bet_container',
        ),
        migrations.RemoveField(
            model_name='longspecialbet',
            name='long_special',
        ),
        migrations.RemoveField(
            model_name='longspecialcontainer',
            name='created_gameweek',
        ),
        migrations.RemoveField(
            model_name='longspecialresult',
            name='completed_gameweek',
        ),
        migrations.RemoveField(
            model_name='longspecialresult',
            name='long_special',
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(related_name='seasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Accumulator',
        ),
        migrations.DeleteModel(
            name='BetContainer',
        ),
        migrations.DeleteModel(
            name='BetPart',
        ),
        migrations.DeleteModel(
            name='LongSpecial',
        ),
        migrations.DeleteModel(
            name='LongSpecialBet',
        ),
        migrations.DeleteModel(
            name='LongSpecialContainer',
        ),
        migrations.DeleteModel(
            name='LongSpecialResult',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
