# Generated by Django 2.1.15 on 2021-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_balance_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away'), ('P', 'Postponed')], default='H', max_length=1),
        ),
    ]
