# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=255)),
                ('awayteam', models.CharField(max_length=255)),
                ('homenumerator', models.IntegerField(default=0)),
                ('homedenominator', models.IntegerField(default=1)),
                ('drawnumerator', models.IntegerField(default=0)),
                ('drawdenominator', models.IntegerField(default=1)),
                ('awaynumerator', models.IntegerField(default=0)),
                ('awaydenominator', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(verbose_name='bets deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
    ]
