# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:20
from __future__ import unicode_literals

import bets.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('bets', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('bets', wagtail.wagtailcore.fields.StreamField([('bets_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('stake', wagtail.wagtailcore.blocks.DecimalBlock(required=True)), ('bets', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('game', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(bets.models.Game, required=True)), ('result', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')]))])))])))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.CharField(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')], default='H', max_length=1),
        ),
    ]
