# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20170513_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='betpage',
            name='gameweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
    ]
