# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_betpage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betpage',
            name='user',
        ),
    ]
