# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:34
from __future__ import unicode_literals

import bets.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20170514_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bets', wagtail.wagtailcore.fields.StreamField([('bets_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('stake', wagtail.wagtailcore.blocks.DecimalBlock(required=True)), ('gameresults', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('game', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(bets.models.Game, required=True)), ('result', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')]))])))])))])),
                ('gameweek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.Gameweek')),
            ],
        ),
    ]
