# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('bets', '0010_bet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betpage',
            name='gameweek',
        ),
        migrations.RemoveField(
            model_name='betpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BetPage',
        ),
    ]
