# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0011_auto_20170528_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetGameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('H', 'Home'), ('D', 'Draw'), ('A', 'Away')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BetSlim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('betcontainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.BetContainer')),
            ],
        ),
        migrations.AddField(
            model_name='betgameresult',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.BetSlim'),
        ),
        migrations.AddField(
            model_name='betgameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game'),
        ),
    ]
