# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0014_auto_20170916_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='weekly_allowance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=99),
        ),
    ]
