# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0015_season_weekly_allowance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='gameweek',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
