# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0017_auto_20170930_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameweek',
            name='deadline',
        ),
        migrations.AddField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2017, 10, 22)),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='deadline_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='spiel',
            field=models.TextField(default=None),
        ),
    ]
