# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0018_auto_20171022_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2017, 11, 19)),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='spiel',
            field=models.TextField(blank=True, default=None),
        ),
    ]
