# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0019_auto_20171119_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2017, 12, 24)),
        ),
    ]
