# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0020_auto_20171224_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='position',
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2017, 12, 27)),
        ),
    ]
