# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0023_auto_20180521_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancemap',
            name='gameweek',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='balancemap',
        ),
        migrations.DeleteModel(
            name='BalanceMap',
        ),
    ]
