# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0024_auto_20180521_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='commissioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(related_name='season_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2018, 5, 25)),
        ),
    ]
