# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0027_joinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('numerator', models.IntegerField(default=0)),
                ('denominator', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.BetContainer')),
                ('long_special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.LongSpecial')),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('allowance', models.DecimalField(decimal_places=2, default=100.0, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name='LongSpecialResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2018, 7, 30)),
        ),
        migrations.AddField(
            model_name='longspecialresult',
            name='completed_gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
        migrations.AddField(
            model_name='longspecialresult',
            name='long_special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Game'),
        ),
        migrations.AddField(
            model_name='longspecialcontainer',
            name='created_gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gameweek'),
        ),
        migrations.AddField(
            model_name='longspecial',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.LongSpecialContainer'),
        ),
    ]
