# Generated by Django 2.1.15 on 2020-12-31 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longspecialresult',
            name='result',
        ),
        migrations.AlterField(
            model_name='longspecialresult',
            name='long_special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambling.LongSpecial'),
        ),
    ]
